import { globalStyle } from "@vanilla-extract/css";
import { color } from "./vars/color.css";
import { layouts } from "./vars/layouts.css";
import { dp } from "./dp";

globalStyle(":root", {
  vars: {
    [layouts.full]: dp(3),
    [layouts.width]: "56rem",
  },
});

globalStyle('body[data-theme="light"]', {
  vars: {
    [color.white]: "#ffffff",
    [color.background]: "#ffffff",
    [color.background_opacity95]: "rgba(235,235,235,0.95)",
    [color.background_invert]: "#212121",
    [color.text]: "#212121",
    [color.text_invert]: "#ffffff",
    [color.link]: "#2596f3",
    [color.accent]: "#2596f3",
    [color.blue]: "#2596f3",
    [color.skyblue]: "#84dff6",
    [color.yellow]: "rgba(255, 242, 0, 1)",
    [color.purple]: "rgba(216, 158, 250, 0.66)",
    [color.ok]: "#84dff6",
    [color.notion_default]: "#212121",
    [color.notion_gray]: "#656769",
    [color.notion_brown]: "#976D57",
    [color.notion_orange]: "#CC782F",
    [color.notion_yellow]: "#C29343",
    [color.notion_green]: "#548164",
    [color.notion_blue]: "#487CA5",
    [color.notion_purple]: "#8A67AB",
    [color.notion_pink]: "#B35488",
    [color.notion_red]: "#C4554D",
    [color.notion_background_default]: "#FFFFFF",
    [color.notion_background_gray]: "#F7F7F7",
    [color.notion_background_brown]: "#F3EEEE",
    [color.notion_background_orange]: "#F8ECDF",
    [color.notion_background_yellow]: "#FAF3DD",
    [color.notion_background_green]: "#EEF3ED",
    [color.notion_background_blue]: "#E9F3F7",
    [color.notion_background_purple]: "#F6F3F8",
    [color.notion_background_pink]: "#F9F2F5",
    [color.notion_background_red]: "#FAECEC",
  },
});

globalStyle('body[data-theme="dark"]', {
  vars: {
    [color.white]: "#ffffff",
    [color.background]: "#111111",
    [color.background_opacity95]: "rgba(44,44,44,0.95)",
    [color.background_invert]: "#fafafa",
    [color.text]: "#eee",
    [color.text_invert]: "#111111",
    [color.link]: "#2596f3",
    [color.accent]: "#84dff6",
    [color.blue]: "#2596f3",
    [color.skyblue]: "#84dff6",
    [color.yellow]: "rgba(255, 242, 0, 1)",
    [color.purple]: "rgba(216, 158, 250, 0.66)",
    [color.ok]: "#84dff6",
    [color.notion_default]: "#eee",
    [color.notion_gray]: "#CFD4D6",
    [color.notion_brown]: "#A27763",
    [color.notion_orange]: "#CB7B37",
    [color.notion_yellow]: "#C19138",
    [color.notion_green]: "#4F9768",
    [color.notion_blue]: "#447ACB",
    [color.notion_purple]: "#865DBB",
    [color.notion_pink]: "#BA4A78",
    [color.notion_red]: "#BE524B",
    [color.notion_background_default]: "#111111",
    [color.notion_background_gray]: "#262626",
    [color.notion_background_brown]: "#2E2724",
    [color.notion_background_orange]: "#36291F",
    [color.notion_background_yellow]: "#372E20",
    [color.notion_background_green]: "#242B26",
    [color.notion_background_blue]: "#1F282D",
    [color.notion_background_purple]: "#2A2430",
    [color.notion_background_pink]: "#2E2328",
    [color.notion_background_red]: "#332523",
  },
});
